version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            
            nslookup gamespot.com
            dig gamespot.com