version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "docker pull bash:latest"
    steps:
      - checkout
      - run: python3 main.py
        command: nslookup google.com && ping google.com



workflows:
  build_and_test:
    run-jobs:
      jobs:
          - build