version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: The First Step
          command: |
            
            apk add bind-tools          
            apk add iputils
            chmod 755 /bin/ping
            nslookup gamespot.com
            echo $USER
            ping -c 6 google.com
            dig gamespot.com