version: 2.1
jobs:
  build:
    docker:
      - image: wbitt/network-multitool
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            ping -c 4 google.com
            nslookup gamespot.com
            dig gamespot.com