version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: The First Step
          command: |
            apk add iputils
            apk add bind-tools          
            apk add net-tools
            chmod 4755 /bin/ping
            nslookup gamespot.com
            ping -c 6 google.com
            dig gamespot.com