version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: The First Step
          command: |
            ping 4 -c google.com
            apk update -y && apk add bind-tools -y
            nslookup gamespot.com
            dig gamespot.com