version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: The First Step
          command: |
            apk add bind-tools          
            apk add net-tools
            nslookup gamespot.com
            ping 4 -c google.com
            dig gamespot.com